/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FacultyRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
});
export const FacultyRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : FacultyRequestStatus,
  'timing' : IDL.Nat,
  'submittedAt' : IDL.Int,
  'description' : IDL.Text,
  'inTime' : IDL.Opt(IDL.Int),
  'facultyName' : IDL.Text,
  'outTime' : IDL.Opt(IDL.Int),
});
export const UserRole = IDL.Variant({
  'principal' : IDL.Null,
  'security' : IDL.Null,
  'faculty' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'getAllApprovedRequests' : IDL.Func([], [IDL.Vec(FacultyRequest)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(FacultyRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getPendingRequests' : IDL.Func([], [IDL.Vec(FacultyRequest)], ['query']),
  'getRequest' : IDL.Func([IDL.Nat], [FacultyRequest], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordFacultyInTime' : IDL.Func([IDL.Nat], [], []),
  'recordFacultyOutTime' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'updateRequestStatus' : IDL.Func([IDL.Nat, FacultyRequestStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FacultyRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
  });
  const FacultyRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : FacultyRequestStatus,
    'timing' : IDL.Nat,
    'submittedAt' : IDL.Int,
    'description' : IDL.Text,
    'inTime' : IDL.Opt(IDL.Int),
    'facultyName' : IDL.Text,
    'outTime' : IDL.Opt(IDL.Int),
  });
  const UserRole = IDL.Variant({
    'principal' : IDL.Null,
    'security' : IDL.Null,
    'faculty' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'getAllApprovedRequests' : IDL.Func(
        [],
        [IDL.Vec(FacultyRequest)],
        ['query'],
      ),
    'getAllRequests' : IDL.Func([], [IDL.Vec(FacultyRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getPendingRequests' : IDL.Func([], [IDL.Vec(FacultyRequest)], ['query']),
    'getRequest' : IDL.Func([IDL.Nat], [FacultyRequest], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordFacultyInTime' : IDL.Func([IDL.Nat], [], []),
    'recordFacultyOutTime' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'updateRequestStatus' : IDL.Func([IDL.Nat, FacultyRequestStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };