/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FacultyRequest {
  'id' : bigint,
  'status' : FacultyRequestStatus,
  'timing' : bigint,
  'submittedAt' : bigint,
  'description' : string,
  'inTime' : [] | [bigint],
  'facultyName' : string,
  'outTime' : [] | [bigint],
}
export type FacultyRequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'declined' : null };
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'principal' : null } |
  { 'security' : null } |
  { 'faculty' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'getAllApprovedRequests' : ActorMethod<[], Array<FacultyRequest>>,
  'getAllRequests' : ActorMethod<[], Array<FacultyRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getPendingRequests' : ActorMethod<[], Array<FacultyRequest>>,
  'getRequest' : ActorMethod<[bigint], FacultyRequest>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordFacultyInTime' : ActorMethod<[bigint], undefined>,
  'recordFacultyOutTime' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRequest' : ActorMethod<[string, string, bigint], bigint>,
  'updateRequestStatus' : ActorMethod<
    [bigint, FacultyRequestStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];